/*
 * SettingsIpcHandler.qml — IPC handler for settings-ui
 *
 * Lives in: dots-extra/quickshell/ii/modules/settings/
 *
 * Provides IPC handler "settingsui" with methods:
 *   getGlobalOpacity()         → real
 *   setGlobalOpacity(val)      → bool
 *   listKeybinds()             → array
 *   getKeybindEnabled(desc)     → bool
 *   setKeybindEnabled(desc, enabled) → bool
 *   addKeybind(bindObj)        → bool
 *   deleteKeybind(desc)        → bool
 *
 * Usage from shell:
 *   qs -c ii ipc call settingsui getGlobalOpacity
 *   qs -c ii ipc call settingsui setGlobalOpacity 0.75
 *   qs -c ii ipc call settingsui listKeybinds
 *   qs -c ii ipc call settingsui setKeybindEnabled "SUPER RETURN exec kitty" false
 */

pragma Singleton
pragma ComponentBehavior: Bound
import QtQuick
import Quickshell
import Quickshell.Io
import qs.modules.common
import qs.modules.common.functions
import qs.services

Singleton {
    function trimmedHome(): string {
        return FileUtils.trimFileProtocol(Directories.home);
    }

    id: root
    objectName: "settingsIpcHandler" // forces instantiation when referenced

    IpcHandler {
        target: "settingsui"

        // ─── Opacity ───────────────────────────────────────────────────────────

        function getGlobalOpacity() {
            return Config.options?.appearance?.globalOpacity ?? 0.9;
        }

        function setGlobalOpacity(val: string) {
            let parsed = parseFloat(val);
            if (isNaN(parsed)) return false;
            parsed = Math.max(0.1, Math.min(1.0, parsed));
            if (!Config.options.appearance) Config.options.appearance = {};
            Config.options.appearance.globalOpacity = parsed;
            return true;
        }

        // ─── Keybinds list ───────────────────────────────────────────────────

        function listKeybinds() {
            try {
                // Use ~/.local/bin/hyprctl which auto-detects the Hyprland socket
                const { exitCode, stdout } = Quickshell.execSync(["bash", "-c", "$HOME/.local/bin/hyprctl binds -j"]);
                if (exitCode !== 0 || !stdout || !stdout.trim()) return [];
                const parsed = JSON.parse(stdout.trim());
                return Array.isArray(parsed) ? parsed : [];
            } catch (e) { return []; }
        }

        function getKeybindEnabled(desc: string) {
            let disabled = Config.options.keybinds?.disabled || [];
            return !disabled.includes(desc);
        }

        function setKeybindEnabled(desc: string, enabled: bool) {
            if (!Config.options.keybinds) Config.options.keybinds = {};
            let disabled = Config.options.keybinds.disabled || [];
            if (enabled) {
                disabled = disabled.filter(d => d !== desc);
            } else {
                if (!disabled.includes(desc)) disabled.push(desc);
            }
            Config.options.keybinds.disabled = disabled;
            writeDisableBinds();
            hyprctlReload();
            return true;
        }

        function addKeybind(bindObj: string) {
            if (!bindObj) return false;
            let obj = (typeof bindObj === "string") ? JSON.parse(bindObj) : bindObj;
            let line = formatBindLine(obj);
            appendToFile(hyprCustomBindsPath(), line);
            hyprctlReload();
            return true;
        }

        function deleteKeybind(desc: string) {
            removeBindFromFile(hyprCustomBindsPath(), desc);
            hyprctlReload();
            return true;
        }

        // ─── Paths ──────────────────────────────────────────────────────────

        function hyprCustomBindsPath() {
            return trimmedHome() + "/.config/hypr/hyprland/keybinds.lua";
        }

        function hyprDisableBindsPath() {
            return trimmedHome() + "/.config/hypr/custom/disable-binds.lua";
        }

        function hyprctlReload() {
            Quickshell.execDetached(["hyprctl", "reload"]);
        }

        // ─── File writers (bash heredoc) ─────────────────────────────────────

        function writeDisableBinds() {
            let disabled = Config.options.keybinds?.disabled || [];
            let keybinds = listKeybindsProc.lastBindList || [];
            let lines = [
                "-- Auto-generated by illogical-impulse settings",
                "-- Disabled keybinds (shadowed with bindl so original bind never fires)",
                ""
            ];
            for (let i = 0; i < keybinds.length; i++) {
                let bind = keybinds[i];
                if (disabled.includes(bind.description)) {
                    let mods = (bind.modifiers || []).join(",");
                    let keyPart = mods ? mods + "," + bind.key : bind.key;
                    let dispatcher = bind.dispatcher || "";
                    let arg = bind.arg || "";
                    lines.push("bindl = " + keyPart + ", " + dispatcher + ", " + arg + " -- disabled via settings");
                }
            }
            let content = lines.join("\n") + "\n";
            writeFile(hyprDisableBindsPath(), content);
        }

        // Generic write: overwrites path with content
        function writeFile(path: string, content: string) {
            let escapedPath = path.replace(/'/g, "'\"'\"'");
            let escapedContent = content.replace(/'/g, "'\"'\"'");
            writeFileProcess.running = false;
            writeFileProcess.command = [
                "bash", "-c",
                "cat > '" + escapedPath + "' << 'IIEOF'\n" + escapedContent + "\nIIEOF"
            ];
            writeFileProcess.running = true;
        }

        // Append content to file
        function appendToFile(path: string, content: string) {
            let escapedPath = path.replace(/'/g, "'\"'\"'");
            let escapedContent = content.replace(/'/g, "'\"'\"'");
            appendProcess.running = false;
            appendProcess.command = [
                "bash", "-c",
                "cat >> '" + escapedPath + "' << 'IIEOF'\n" + escapedContent + "\nIIEOF"
            ];
            appendProcess.running = true;
        }

        // Remove lines matching description from file
        function removeBindFromFile(path: string, desc: string) {
            let escapedPath = path.replace(/'/g, "'\"'\"'");
            let escapedDesc = desc.replace(/'/g, "'\"'\"'");
            removeProcess.running = false;
            removeProcess.command = [
                "bash", "-c",
                "grep -vF -- '" + escapedDesc + "' '" + escapedPath + "' > '" + escapedPath + ".tmp' && mv '" + escapedPath + ".tmp' '" + escapedPath + "'"
            ];
            removeProcess.running = true;
        }
    }

    // ─── Internal helper ─────────────────────────────────────────────────

    function formatBindLine(bindObj) {
        let mods = (bindObj.modifiers || []).join(",");
        let fullKey = mods ? mods + "," + bindObj.key : bindObj.key;
        let desc = bindObj.description ? (" -- " + bindObj.description) : "";
        let arg = bindObj.arg || "";
        return "hl.bind(\"" + fullKey + "\", hl.dsp." + bindObj.dispatcher + "(\"" + arg + "\"))" + desc;
    }

    // ─── Background processes ──────────────────────────────────────────────

    Process {
        id: writeFileProcess
        running: false
        stdout: StdioCollector { onStreamFinished: {} }
    }

    Process {
        id: appendProcess
        running: false
        stdout: StdioCollector { onStreamFinished: {} }
    }

    Process {
        id: removeProcess
        running: false
        stdout: StdioCollector { onStreamFinished: {} }
    }

    Process {
        id: listKeybindsProc
        property var lastBindList: []
        command: ["bash", "-c", "$HOME/.local/bin/hyprctl binds -j"]
        stdout: StdioCollector {
            onStreamFinished: {
                try { lastBindList = JSON.parse(text || "[]"); } catch (e) { lastBindList = []; }
            }
        }
    }
}
