/*
 * SettingsIpcHandler.qml — IPC handler for settings-ui
 *
 * Lives in: dots-extra/quickshell/ii/modules/settings/
 *
 * Provides IPC handler "settingsui" with methods:
 *   getGlobalOpacity()         → real
 *   setGlobalOpacity(val)      → bool
 *   listKeybinds()             → array
 *   getKeybindEnabled(desc)     → bool
 *   setKeybindEnabled(desc, enabled) → bool
 *   addKeybind(bindObj)        → bool
 *   deleteKeybind(desc)        → bool
 *
 * Usage from shell:
 *   qs -c ii ipc call settingsui getGlobalOpacity
 *   qs -c ii ipc call settingsui setGlobalOpacity 0.75
 *   qs -c ii ipc call settingsui listKeybinds
 *   qs -c ii ipc call settingsui setKeybindEnabled "SUPER RETURN exec kitty" false
 */

pragma ComponentBehavior: Bound
import QtQuick
import Quickshell
import Quickshell.Io
import qs.modules.common
import qs.services

Scope {
    id: root

    IpcHandler {
        target: "settingsui"

        // ─── Opacity ───────────────────────────────────────────────────────────

        function getGlobalOpacity() {
            try {
                let cfgPath = Directories.config.replace(/^file:\/\//, "") + "/illogical-impulse/config.json";
                let { exitCode, stdout } = Quickshell.execSync(["python3", "-c", "import json; d=json.load(open('" + cfgPath + "')); print(d.get('appearance',{}).get('globalOpacity',0.9))"]);
                if (exitCode !== 0) return 0.90;
                let val = parseFloat(stdout.trim());
                return isNaN(val) ? 0.90 : val;
            } catch (e) { return 0.90; }
        }

        function setGlobalOpacity(val) {
            let parsed = parseFloat(val);
            if (isNaN(parsed)) return false;
            parsed = Math.max(0.1, Math.min(1.0, parsed));
            let cfgPath = Directories.config.replace(/^file:\/\//, "") + "/illogical-impulse/config.json";
            let escapedPath = cfgPath.replace(/"/g, '\\"');
            let script = "python3 -c \"import json; cfg=json.load(open(\\\"" + escapedPath + "\\\")); cfg['appearance']['globalOpacity']=" + parsed + "; json.dump(cfg,open(\\\"" + escapedPath + "\\\"+'.tmp','w'),indent=2); import os; os.replace(\\\"" + escapedPath + "\\\"+'.tmp',\\\"" + escapedPath + "\\\")\"";
            Quickshell.execDetached(["bash", "-c", script]);
            return true;
        }

        // ─── Keybinds list ───────────────────────────────────────────────────

        function listKeybinds() {
            listKeybindsProc.running = false;
            listKeybindsProc.running = true;
            return listKeybindsProc.lastBindList || [];
        }

        function getKeybindEnabled(desc) {
            let disabled = Config.options.keybinds.disabled || [];
            return !disabled.includes(desc);
        }

        function setKeybindEnabled(desc, enabled) {
            let disabled = Config.options.keybinds.disabled || [];
            if (enabled) {
                disabled = disabled.filter(d => d !== desc);
            } else {
                if (!disabled.includes(desc)) disabled.push(desc);
            }
            Config.options.keybinds.disabled = disabled;
            writeDisableBinds();
            hyprctlReload();
            return true;
        }

        function addKeybind(bindObj) {
            if (!bindObj) return false;
            let line = formatBindLine(bindObj);
            appendToFile(hyprCustomBindsPath(), line);
            hyprctlReload();
            return true;
        }

        function deleteKeybind(desc) {
            removeBindFromFile(hyprCustomBindsPath(), desc);
            hyprctlReload();
            return true;
        }

        // ─── Paths ──────────────────────────────────────────────────────────

        function hyprCustomBindsPath() {
            return Directories.home + "/.config/hypr/custom/keybinds.lua";
        }

        function hyprDisableBindsPath() {
            return Directories.home + "/.config/hypr/custom/disable-binds.lua";
        }

        function hyprctlReload() {
            Quickshell.execDetached(["hyprctl", "reload"]);
        }

        // ─── File writers (bash heredoc) ─────────────────────────────────────

        function writeDisableBinds() {
            let disabled = Config.options.keybinds.disabled || [];
            let keybinds = listKeybindsProc.lastBindList || [];
            let lines = [
                "-- Auto-generated by illogical-impulse settings",
                "-- Disabled keybinds (shadowed with bindl so original bind never fires)",
                ""
            ];
            for (let i = 0; i < keybinds.length; i++) {
                let bind = keybinds[i];
                if (disabled.includes(bind.description)) {
                    let mods = (bind.modifiers || []).join(",");
                    let keyPart = mods ? mods + "," + bind.key : bind.key;
                    let dispatcher = bind.dispatcher || "";
                    let arg = bind.arg || "";
                    lines.push("bindl = " + keyPart + ", " + dispatcher + ", " + arg + " -- disabled via settings");
                }
            }
            let content = lines.join("\n") + "\n";
            writeFile(hyprDisableBindsPath(), content);
        }

        function formatBindLine(bindObj) {
            let mods = (bindObj.modifiers || []).join(",");
            let fullKey = mods ? mods + "," + bindObj.key : bindObj.key;
            let desc = bindObj.description ? (" -- " + bindObj.description) : "";
            let arg = bindObj.arg || "";
            return "hl.bind(\"" + fullKey + "\", hl.dsp." + bindObj.dispatcher + "(\"" + arg + "\"))" + desc;
        }

        // Generic write: overwrites path with content
        function writeFile(path, content) {
            let escapedPath = path.replace(/'/g, "'\"'\"'");
            let escapedContent = content.replace(/'/g, "'\"'\"'");
            writeFileProcess.running = false;
            writeFileProcess.command = [
                "bash", "-c",
                "cat > '" + escapedPath + "' << 'IIEOF'\n" + escapedContent + "\nIIEOF"
            ];
            writeFileProcess.running = true;
        }

        // Append content to file
        function appendToFile(path, content) {
            let escapedPath = path.replace(/'/g, "'\"'\"'");
            let escapedContent = content.replace(/'/g, "'\"'\"'");
            appendProcess.running = false;
            appendProcess.command = [
                "bash", "-c",
                "cat >> '" + escapedPath + "' << 'IIEOF'\n" + escapedContent + "\nIIEOF"
            ];
            appendProcess.running = true;
        }

        // Remove lines matching description from file
        function removeBindFromFile(path, desc) {
            let escapedPath = path.replace(/'/g, "'\"'\"'");
            let escapedDesc = desc.replace(/'/g, "'\"'\"'");
            removeProcess.running = false;
            removeProcess.command = [
                "bash", "-c",
                "grep -vF -- '" + escapedDesc + "' '" + escapedPath + "' > '" + escapedPath + ".tmp' && mv '" + escapedPath + ".tmp' '" + escapedPath + "'"
            ];
            removeProcess.running = true;
        }

        // ─── Background processes ──────────────────────────────────────────

        Process {
            id: writeFileProcess
            running: false
            stdout: StdioCollector { onStreamFinished: {} }
        }

        Process {
            id: appendProcess
            running: false
            stdout: StdioCollector { onStreamFinished: {} }
        }

        Process {
            id: removeProcess
            running: false
            stdout: StdioCollector { onStreamFinished: {} }
        }

        Process {
            id: listKeybindsProc
            property var lastBindList: []
            command: ["bash", "-c", "hyprctl binds -j"]
            stdout: StdioCollector {
                onStreamFinished: {
                    try { lastBindList = JSON.parse(text || "[]"); } catch (e) { lastBindList = []; }
                }
            }
        }
    }
}
